server:
  port: 3003
spring:
  datasource:
    url: jdbc:postgresql://210.115.230.166:10654/mydb
    driver-class-name: org.postgresql.Driver
    username: dictation
    password: dic123
    
    
servlet:
  multipart:
    enabled: true
    file-size-threshold: 1MB
    location: C:/Temp
    max-file-size: 100MB
    max-request-size: 100MB    

mybatis:
 mapper-locations: classpath:mapper/**/*.xml
 type-aliases-package: com.dictation.vo